import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Categories",
  description: "Generated by Ecommerce App",
};

export default function layout({
 children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        {children}
    </div>
  )
}
