import type { Metadata } from "next";
import "./globals.css";
import Navigation from "../components/Navigation";

import { Geist } from 'next/font/google'
 
const geist = Geist({
  subsets: ['latin'],
})
 

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by Ecommerce App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={geist.className}
    >
      <body>
        <Navigation/>
        <main>{children}</main>
      </body>
    </html>
  );
}
