import ProductList from "@/components/ProductList";
import Spinner from "@/components/spinner";
import { Suspense } from "react";

export const metadata = {
    title: "Products",
    description: "Generated by Ecommerce App",
};
interface props {
     searchParams: Promise<{
       rating?: string;
        query?: string;
  }>;
}
export const revalidate = 0;

export default async function Products({ searchParams }: props) {
    const { rating, query } = await searchParams;
    const filteredProducts = rating ?? "all";
      const querys =query ?? "";
    // console.log(filteredProducts);

    return (
        <div>
                <Suspense fallback={<Spinner />}>
                    <ProductList filteredProducts={filteredProducts} searchValue={querys} />
                </Suspense>
        </div>

    )
}
