import ProductList from "@/components/ProductList";
import Spinner from "@/components/spinner";
import { Suspense } from "react";

export const metadata = {
    title: "Products",
    description: "Generated by Ecommerce App",
};

interface props {
    searchParams: Promise<{
        query?: string;
        category?: string;
    }>;
}

export const revalidate = 0;

export default async function Products({ searchParams }: props) {
    const { query, category } = await searchParams;
    const querys = query ?? "";
    const categoryValue = category ?? "";

    return (
        <div>
            <Suspense fallback={<Spinner />}>
                <ProductList searchValue={querys} categoryValue={categoryValue} />
            </Suspense>
        </div>
    )
}